### ISSUE TITLE
Heroes: Design It!

### ISSUE THREAD

**Issue by jeremyfleischer** [DigitalDenizen/FearAndLight#132]
Design a handful of different genders and frame sizes
- [x] Add skin tones (dark, medium, light)
- [x] Add genders (male/female)
- [x] Idle animation
- [x] Walk animation
- [x] Attack animation
- [x] Roll animation
- [x] Hurt animation
- [x] Jump animation
- [x] Jump attack animation
- [x] Death animation
- [x] Poop animation
- [x] Bone armor set (test)
- [x] Big export

**Comment by DigitalDenizen** [comment]
This card is more than a 6, but we're calling it a 6.
