### ISSUE TITLE
Mud Wall: Code it!

### ISSUE THREAD

**Issue by RunsWithBuns420** [DigitalDenizen/FearAndLight#4]
- [x] Make mud wall solid object
- [x] Reduce mud wall health when attacked
- [x] Mud Wall destruction 
- [x] Heroes do not destroy mud wall
- [x] Hero projectiles disappear after hitting structures
- [x] Puff appears when fireball hits it
- [x] Merge into master

**Comment by DigitalDenizen** [comment]
Do you know how to make a PR, Fred?
